version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresNext
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
    ports:
      - "6543:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local
