import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Link from "next/link";

import paths from "@/utils/paths";
import AuthHeader from "@/components/auth-header";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="p-2 flex gap-6">
            <Link href={paths.home()}>Home</Link>
            <Link href={paths.dashboard()}>Dashboard</Link>
            <Link href={paths.protectedExample()}>Protected Route</Link>
            <Suspense>
              <AuthHeader></AuthHeader>
            </Suspense>
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
